server:
  port: 8081
  error:
    include-message: always

my:
  kafka:
    notification:
      topic: notification.created

spring:
  application:
    name: bookpersistence
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/kafkabookpersistence
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: book-persistence
